[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "flask>=3.1.0",
    "matplotlib>=3.10.1",
    "python-dotenv>=1.1.0",
    "tzdata>=2025.2",
]
